Repository dotnet/corefx, pull requests merged in 2020-07, with the labels that each got.

#42945 note that the crypto article moved
  Documentation/architecture/cross-platform-cryptography.md
Labels: area-System.Security

#42946 Updated build pools
  buildpipeline/DotNet-CoreFx-Trusted-Windows-NoTest.json
  buildpipeline/DotNet-CoreFx-Trusted-Windows.json
Labels: area-Infrastructure

#42948 Update Branding to 3.1.7
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  src/System.Data.Common/src/Configurations.props
  src/System.Data.Common/src/Resources/Strings.resx
  src/System.Data.Common/src/System.Data.Common.csproj
  src/System.Data.Common/src/System/Data/Common/ObjectStorage.cs
  src/System.Data.Common/src/System/Data/DataColumn.cs
  src/System.Data.Common/src/System/Data/DataException.cs
  src/System.Data.Common/src/System/Data/DataSet.cs
  src/System.Data.Common/src/System/Data/DataTable.cs
  src/System.Data.Common/src/System/Data/Filter/FunctionNode.cs
  src/System.Data.Common/src/System/Data/LocalAppContextSwitches.cs
  src/System.Data.Common/src/System/Data/TypeLimiter.cs
  src/System.Data.Common/tests/System.Data.Common.Tests.csproj
  src/System.Data.Common/tests/System/Data/RestrictedTypeHandlingTests.cs
Labels: area-System.Data

#42941 [release/3.1] Port SafeProcessHandle.Unix: fix missing DangerousRelease
  src/System.Diagnostics.Process/src/Microsoft/Win32/SafeHandles/SafeProcessHandle.Unix.cs
Labels: Servicing-approved, area-System.Diagnostics.Process

#42938 [Release/3.1] Fix infinite loop when end of stream is reached
  src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SslOverTdsStream.cs
Labels: Servicing-approved, area-System.Data.SqlClient

#42937 [Release 3.1] Avoid enlistment of pooled connection in aborted transaction
  src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDelegatedTransaction.cs
Labels: Servicing-approved, area-System.Data.SqlClient

#42907 [Release/3.1] Address MARS TDS header contained errors
  src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs
  src/System.Data.SqlClient/tests/ManualTests/SQL/AsyncTest/AsyncCancelledConnectionsTest.cs
  src/System.Data.SqlClient/tests/ManualTests/System.Data.SqlClient.ManualTesting.Tests.csproj
Labels: Servicing-approved, area-System.Data.SqlClient

#42942 [release/3.1] Ignore 0-byte responses from AIA fetch.
  src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CertificateAssetDownloader.cs
Labels: Servicing-approved, area-System.Security

#42949 update branding for 2.1.21
  src/System.Data.Common/src/Resources/Strings.resx
  src/System.Data.Common/src/System.Data.Common.csproj
  src/System.Data.Common/src/System/Data/Common/ObjectStorage.cs
  src/System.Data.Common/src/System/Data/DataColumn.cs
  src/System.Data.Common/src/System/Data/DataException.cs
  src/System.Data.Common/src/System/Data/DataSet.cs
  src/System.Data.Common/src/System/Data/DataTable.cs
  src/System.Data.Common/src/System/Data/Filter/FunctionNode.cs
  src/System.Data.Common/src/System/Data/LocalAppContextSwitches.cs
  src/System.Data.Common/src/System/Data/TypeLimiter.cs
  src/System.Data.Common/tests/System.Data.Common.Tests.csproj
  src/System.Data.Common/tests/System/Data/RestrictedTypeHandlingTests.netcoreapp.cs
Labels: area-System.Data

#42934 [release/2.1] add new Ubuntu & Alpine versions to RID graph
  pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
  src/packages.builds
Labels: Servicing-approved, area-Infrastructure

#42954 Updates pipelines queues
  buildpipeline/DotNet-CoreFx-Trusted-Windows-NoTest.json
  buildpipeline/DotNet-CoreFx-Trusted-Windows.json
Labels: area-Infrastructure

#42952 add packaging for system.data.sqlclient
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  pkg/Microsoft.Windows.Compatibility/Microsoft.Windows.Compatibility.pkgproj
  src/System.Data.SqlClient/Directory.Build.props
  src/packages.builds
Labels: area-Infrastructure

#42956 Locks esrp version
  buildpipeline/DotNet-Trusted-Publish.json
Labels: area-Infrastructure

#42944 Use Azure Artifacts feeds instead of MyGet
  dir.props
  init-tools.cmd
  init-tools.sh
  pkg/Microsoft.Windows.Compatibility/tests/publishcompatibilityassets.ps1
  pkg/test/testPackages.proj
  run-test.sh
  src/NuGet.config
Labels: area-System.ComponentModel.DataAnnotations

#42960 Unlocks esrp version
  buildpipeline/DotNet-Trusted-Publish.json
Labels: area-Infrastructure
