Repository dotnet/corefx, pull requests merged in 2020-08, with the labels that each got.

#42963 Update branding for 2.1.22
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: area-Infrastructure

#42962 Update Branding to 3.1.8
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  src/packages.builds
Labels: area-Infrastructure

#42968 release/3.1 add macOS11 to RID graph
  eng/Packaging.props
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: Servicing-consider, area-Infrastructure

#42969 release/2.1 add maccOS 11 to rid graph
  pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
  src/packages.builds
Labels: area-Infrastructure

#42971 release/3.1: add also osx 10.16 fo compact reasons
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
Labels: area-Infrastructure

#42970 release/2.1: add also osx 10.16 fo compact reasons
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
Labels: area-Infrastructure

#42974 Use legacy MyGet feed.
  dir.props
  init-tools.cmd
  init-tools.sh
  pkg/test/testPackages.proj
  src/NuGet.config
Labels: area-Infrastructure

#42973 Use legacy MyGet feed
  dir.props
  init-tools.cmd
  init-tools.sh
  pkg/test/testPackages.proj
  src/NuGet.config
Labels: area-Infrastructure

#42972 Use legacy MyGet feeds
  dir.props
  init-tools.cmd
  init-tools.sh
  pkg/Microsoft.Windows.Compatibility/tests/publishcompatibilityassets.ps1
  pkg/test/testPackages.proj
  src/NuGet.config
Labels: area-System.ComponentModel.DataAnnotations
