Repository dotnet/corefx, pull requests merged in 2020-04, with the labels that each got.

#42888 [release/3.1] Client certificate authentication on HTTP/2 in WinHttpHandler
  src/Common/src/Interop/Windows/WinHttp/Interop.winhttp_types.cs
  src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs
Labels: Servicing-approved, area-System.Net.Http

#42902 Update branding to preview5
  eng/Versions.props
Labels: area-Infrastructure, auto-merge

#42905 Update branding to rc
  eng/Versions.props
Labels: area-Infrastructure

#42906 [release/3.1-blazor] Fix Http.Json serialization performance by using static options (#35040)
  src/System.Net.Http.Json/src/System/Net/Http/Json/HttpContentJsonExtensions.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs
Labels: area-System.Net.Http

#42908 Disable build of System.Net.Http.WinHttpHandler to avoid problem on net461
  src/System.Net.Http.WinHttpHandler/Directory.Build.props
  src/packages.builds
Labels: area-Infrastructure

#42911 Making System.Net.Http.Json to depend on inbox version of System.Net.Http for net461
  src/System.Net.Http.Json/ref/System.Net.Http.Json.csproj
  src/System.Net.Http.Json/src/System.Net.Http.Json.csproj
Labels: area-System.Net

#42913 Produce stable builds of System.Net.Http.Json
  eng/Versions.props
Labels: area-Infrastructure
