Repository dotnet/corefx, pull requests merged in 2020-05, with the labels that each got.

#42920 Update branding for 3.1.5
  .azure-ci.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/pipelines/corefx-base.yml
  eng/pipelines/freebsd.yml
  eng/pipelines/linux.yml
  eng/pipelines/macos.yml
  eng/pipelines/pre-publish.yml
  eng/pipelines/windows.yml
  global.json
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/System.Private.DataContractSerialization/src/System/Xml/XmlBufferReader.cs
  src/packages.builds
Labels: area-Infrastructure

#42912 Fix serialization of read-only IEnumerable's for DCS
  src/System.Private.DataContractSerialization/src/Resources/Strings.resx
  src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/CollectionDataContract.cs
  src/System.Runtime.Serialization.Xml/tests/DataContractSerializer.cs
Labels: Servicing-approved, area-Serialization

#42914 [release/3.1] Handle additional chain statuses for X509Chain on macOS
  src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_x509chain.c
  src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs
  src/System.Security.Cryptography.X509Certificates/tests/DynamicChainTests.cs
Labels: Servicing-approved, area-System.Security

#42900 [release/3.1] Fix corefx to build on clang 10
  src/Native/Unix/CMakeLists.txt
  src/Native/Unix/configure.cmake
Labels: Servicing-approved, area-Meta

#42915 Merging Blazor feature branch into release/3.1
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  pkg/descriptions.json
  src/System.Net.Http.Json/Directory.Build.props
  src/System.Net.Http.Json/System.Net.Http.Json.sln
  src/System.Net.Http.Json/pkg/System.Net.Http.Json.pkgproj
  src/System.Net.Http.Json/ref/Configurations.props
  src/System.Net.Http.Json/ref/System.Net.Http.Json.cs
  src/System.Net.Http.Json/ref/System.Net.Http.Json.csproj
  src/System.Net.Http.Json/src/Configurations.props
  src/System.Net.Http.Json/src/Resources/Strings.resx
  src/System.Net.Http.Json/src/System.Net.Http.Json.csproj
  src/System.Net.Http.Json/src/System/ArraySegmentExtensions.netstandard.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Get.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Post.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Put.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/HttpContentJsonExtensions.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/JsonContent.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/TranscodingReadStream.cs
  src/System.Net.Http.Json/src/System/Net/Http/Json/TranscodingWriteStream.cs
  src/System.Net.Http.Json/tests/FunctionalTests/Configurations.props
  src/System.Net.Http.Json/tests/FunctionalTests/HttpClientJsonExtensionsTests.cs
  src/System.Net.Http.Json/tests/FunctionalTests/HttpContentJsonExtensionsTests.cs
  src/System.Net.Http.Json/tests/FunctionalTests/JsonContentLoopbackTests.cs
  src/System.Net.Http.Json/tests/FunctionalTests/JsonContentTests.cs
  src/System.Net.Http.Json/tests/FunctionalTests/System.Net.Http.Json.Functional.Tests.csproj
  src/System.Net.Http.Json/tests/FunctionalTests/TestClasses.cs
  src/System.Net.Http.Json/tests/UnitTests/Configurations.props
  src/System.Net.Http.Json/tests/UnitTests/Resources/Strings.resx
  src/System.Net.Http.Json/tests/UnitTests/System.Net.Http.Json.Unit.Tests.csproj
  src/System.Net.Http.Json/tests/UnitTests/TranscodingReadStreamTests.cs
  src/System.Net.Http.Json/tests/UnitTests/TranscodingWriteStreamTests.cs
Labels: area-System.Net

#42910 Ensuring WinHttpHandler will reference TargetingPack assembly versions for netfx builds
  src/System.Net.Http.WinHttpHandler/Directory.Build.props
  src/System.Net.Http.WinHttpHandler/ref/Configurations.props
  src/System.Net.Http.WinHttpHandler/ref/System.Net.Http.WinHttpHandler.csproj
  src/System.Net.Http.WinHttpHandler/src/System.Net.Http.WinHttpHandler.csproj
  src/packages.builds
Labels: Servicing-approved

#42921 Fixing System.Net.Http.Json so that it won't require facades when restored in net461
  src/System.Net.Http.Json/Directory.Build.props
  src/packages.builds
Labels: Servicing-approved

#42922 Reving up version of WinHttpHandler to 4.7.2
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/System.Net.Http.WinHttpHandler/Directory.Build.props
Labels: area-System.Net, auto-merge

#42926 update branding for 2.1.19
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: area-Infrastructure
