Repository dotnet/corefx, pull requests merged in 2020-06, with the labels that each got.

#42928 [release/3.1] update Ubuntu and Alpine RID
  eng/Packaging.props
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
Labels: Servicing-approved

#42930 Branding for 3.1.6
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: area-Infrastructure

#42935 Updates pipelines branches
  buildpipeline/DotNet-CoreFx-Trusted-Linux-Crossbuild.json
  buildpipeline/DotNet-CoreFx-Trusted-Linux.json
  buildpipeline/DotNet-CoreFx-Trusted-Windows-NoTest.json
  buildpipeline/DotNet-CoreFx-Trusted-Windows.json
  buildpipeline/DotNet-Trusted-Publish-Symbols.json
  buildpipeline/DotNet-Trusted-Publish.json
  buildpipeline/DotNet-Trusted-Tests-Publish.json
Labels: area-Infrastructure

#42939 [release/3.1] Fix Path.EndsInDirectorySeparator recursive call
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/Common/src/CoreLib/System/IO/Path.cs
  src/Microsoft.IO.Redist/Directory.Build.props
  src/packages.builds
Labels: Servicing-approved, area-System.IO

#42940 Build the platforms package for shipping
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: area-Infrastructure
