Repository dotnet/corefx, pull requests merged in 2021-05, with the labels that each got.

#43072 Update branding to 2.1.29
  src/packages.builds
Labels: area-System.Security

#43073 Update branding to 3.1.16
  eng/Versions.props
Labels: area-Infrastructure

#43068 [release/3.1] Add CentOS 9 RID and make CentOS 8 arm64 as well
  eng/Packaging.props
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: area-Infrastructure

#43071 Port regex timeout fix (test only change)
  src/Common/tests/CoreFx.Private.TestUtilities/System/PlatformDetection.cs
  src/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs
Labels: area-System.Text.RegularExpressions

#43069 [Release/3.1] Fix wrong data blended with transactions in .NET Core
  src/System.Data.SqlClient/src/System/Data/Common/AdapterUtil.SqlClient.cs
  src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDataReader.cs
  src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs
  src/System.Data.SqlClient/src/System/Data/SqlClient/SqlUtil.cs
  src/System.Data.SqlClient/tests/ManualTests/SQL/TransactionTest/TransactionTest.cs
Labels: Servicing-approved, area-System.Data.SqlClient

#43070 [Release/3.1] Fix race condition issues between SinglePhaseCommit and TransactionEnded events
  src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDelegatedTransaction.cs
Labels: Servicing-approved, area-System.Data.SqlClient

#43074 Merge 3.1.15 internals
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-Infrastructure

#43075 [release/2.1] Update buildtools version
  BuildToolsVersion.txt
  dependencies.props
Labels: area-Infrastructure
