Repository dotnet/corefx, pull requests merged in 2021-06, with the labels that each got.

#43077 Update branding to 3.1.17
  eng/Versions.props
  src/packages.builds
Labels: area-Infrastructure

#43036 Port from 5.0: Fix relro, now, and PIE for Libraries
  src/Native/Unix/CMakeLists.txt
Labels: Servicing-approved

#43082 Fix failing SetCookies_Success test (#53932)
  src/System.Net.Primitives/tests/UnitTests/CookieContainerTest.cs
Labels: area-System.Net
