Repository dotnet/corefx, pull requests merged in 2021-01, with the labels that each got.

#43013 Update branding to 3.1.12
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/packages.builds
Labels: area-Infrastructure

#43009 Add RHEL 9 RID
  pkg/Microsoft.NETCore.Platforms/runtime.compatibility.json
  pkg/Microsoft.NETCore.Platforms/runtime.json
  pkg/Microsoft.NETCore.Platforms/runtimeGroups.props
Labels: api-approved, area-Infrastructure

#43014 Build a new version of platforms package
  eng/Packaging.props
  src/packages.builds
Labels: area-Infrastructure

#43015 [release/2.1] Update buildtools to a version that doesn't reference myget
  BuildToolsVersion.txt
  dependencies.props
Labels: area-Infrastructure

#43017 Port graphics metafile refcount fix to avoid disposing the native image multiple times
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
  src/System.Drawing.Common/dir.props
  src/System.Drawing.Common/src/System/Drawing/Graphics.Unix.cs
  src/System.Drawing.Common/src/System/Drawing/Imaging/Metafile.Unix.cs
  src/packages.builds
Labels: Servicing-approved, area-System.Drawing

#43018 Fix package index
  pkg/Microsoft.Private.PackageBaseline/packageIndex.json
Labels: area-Infrastructure
